config/routes.rb
Rails.application.routes.draw do root 'home#index'
  get 'home/index'
  get 'home/go_to_index'
  get 'contact/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :home
  resources :biographies
  resources :extras
  resources :galleries do
    resources :images
  end
  resources :posters
  resources :principals
  resources :projects, as: "pods", path: "pods"
  resources :ourstory



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/biography.rb
class Biography < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/models/extra.rb
class Extra < ApplicationRecord
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :images
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :gallery
  mount_uploader :picture, PictureUploader
end

app/models/poster.rb
class Poster < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/models/principal.rb
class Principal < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def go_to_index
    
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @gallery = Gallery.find(params[:gallery_id])
    @images = @gallery.images.all
  end

  def show
    @gallery = Gallery.find(params[:essay_id])
    @image = @gallery.images.find(params[:id])
  end

  def new
    @gallery = Gallery.find(params[:essay_id])
    @image = @gallery.images.new
  end

  def create
    @gallery = Gallery.find(params[:essay_id])
    @image = @gallery.images.new(image_params)
    if @image.save
      redirect_to gallery_image_path(@gallery, @image)
    else
      render 'new'
    end
  end

  def edit
    @gallery = Gallery.find(params[:essay_id])
    @image = @gallery.images.find(params[:id])
  end

  def update
    @gallery = Gallery.find(params[:essay_id])
    @image = @gallery.images.find(params[:id])
    if @image.update(image_params)
      redirect_to gallery_image_path(@gallery, @image)
    else
      render 'edit'
    end
  end

  def destroy
    @gallery = Gallery.find(params[:essay_id])
    @image = @gallery.images.find(params[:id])
    @image.destroy

    redirect_to gallery_path(@gallery)
  end

  private
    def image_params
      params.require(:image).permit(:caption, :feature, :picture)
    end

end

app/controllers/posters_controller.rb
class PostersController < ApplicationController

  def index
    @posters = Poster.all
  end

  def show
    @poster = Poster.find(params[:id])
  end

  def new
    @poster = Poster.new
  end

  def create
    @poster = Poster.new(poster_params)
    if @poster.save
      redirect_to poster_path(@poster)
    else
      render 'new'
    end
  end

  def edit
    @poster = Poster.find(params[:id])
  end

  def update
    @poster = Poster.find(params[:id])
    if @poster.update(poster_params)
      redirect_to poster_path(@poster)
    else
      render 'edit'
    end
  end

  def destroy
    @poster = Poster.find(params[:id])
    @poster.destroy

    redirect_to posters_path
  end

  private
    def poster_params
      params.require(:poster).permit(:event, :title, :description, :upcoming, :picture)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @projects = Project.all
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to project_path(@project)
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to project_path(@project)
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  private
    def project_params
      params.require(:project).permit(:title, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/biographies_helper.rb
module BiographiesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/ourstory_helper.rb
module OurstoryHelper
end

app/helpers/posters_helper.rb
module PostersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/byou.html.erb
<!-- ** To be thought about more **
Goal: fill in nav bar with corresponding pod names from the database. 
When you click on each pod, you should take the description and image (from db) and create its own page? --> 

<!DOCTYPE html>
<html lang="en">

<head>
    <title>BYOU</title>
</head>

<div class="container">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">BYOU</a></li>
                <li><a href="#">Terracycle</a></li>
                <li><a href="#">Break Free From Plastic</a></li>
                <li><a href="#">Butterflies and the Bees</a></li>
            </ul>
        </div>
    </nav>

    <body>
        <a href="/pods/byou">byou link</a>
    </body>
</div>


</html>

app/views/projects/index.html.erb
<div class="container-fluid">
  <h1 class="title">Pods</h1>

  <div class="story-section center-block">
    <h2>About</h2>
    <div class="row">
      <div class="body-text">
        <p>At SZW we have a decentralized power structure that allows anyone to be a leader of their own ‘pod’ and create their own project. We call them pods to highlight the idea that they are connected to a larger whole even though they can be distinct entities in themselves. Pods often come in and out of rotation with their leadership are often turn into long-term projects for members.</p>
      </div>
    </div>

    <div class="row">
      <% @projects.order('created_at DESC').each do |project| %>
        <div class="col-md-4 mx-auto story-section">
          <div class="pod-title">
            <h3><%=link_to project.title, pod_path(project) %></h3>
          </div>
          <div class="img-responsive">
            <%=image_tag project.picture.url.to_s, class: "pod-img rounded"%>
          </div>
        </div>
      <%end%>
    </div>

      <!-- 
      <div class="story-section col-md-4">
        <h2>B You</h2>
        <div class="row">
          <div>
            <img src="https://via.placeholder.com/641x749" class="img-responsive">
          </div>
        </div>
      </div>

      <div class="story-section col-md-4">
        <h2>Break Free From Plastic</h2>
        <div class="row">
          <div>
              <img src="https://via.placeholder.com/641x749" class="img-responsive">
          </div>
        </div>
      </div>

      <div class="story-section col-md-4">
        <h2>Terracycle</h2>
        <div class="row">
          <div>
            <img src="https://via.placeholder.com/641x749" class="img-responsive">
          </div>
        </div>
      </div>

      <div class="story-section col-md-4">
        <h2>Butterflies and The Bees</h2>
        <div class="row">
          <div>
            <img src="https://via.placeholder.com/641x749" class="img-responsive">
          </div>
        </div>
      </div>

    -->

  </div>
</div>

app/views/projects/show.html.erb
<div class="container">
    <div class="centered">
        <h1 class="title">Pods</h1>
    </div>

    <!-- nav bar that displays all pods. if current project is displayed, highlight that project -->
    <div class="centered">
        <div>
            <% @projects.order('created_at DESC').each do |project|%>
                <button class="btn btn-default"><%=project.title%> </button>
            <%end%>
        </div>
    </div>

    <!-- description -->

    <div class="description">
        <h2 class="subheading"> <%= @project.title %> </h2>
        <p class="body-text"> <%= @project.description %> </p>
    </div>

    <!-- photos -->

    <div class="pod_photos centered">
        <%= image_tag @project.picture.url.to_s, style: "width: 500px", class: "pod-img" %>
    </div>

    <div style="padding-bottom: 50px">
    </div>
</div>